### ISSUE TITLE
Editor doesn't like CRLF line endings

### ISSUE THREAD

**Issue by jpnielsen** [docb/dbRackCsound#2]
Pasting some lines from Windows Notepad:

<img width="334" alt="image" src="https://user-images.githubusercontent.com/27916597/198345810-82a042cd-8df6-4e87-82ec-b1130c572fb8.png">

The edit is messed up - deletes the wrong lines etc, when CR+LF is pasted into it.
It probably expects Mac/Linux LF only.

Also, it would be nice with a "delete" in the right click menu for the text - if 
I use select all, and "cut" - my copy/paste buffer is overwritten. Windows "standard" has "Delete" too.

**Comment by docb** [comment]
ok, the first one seems to be in the API - Fundamental Notes seems also having a problem with that. i'll try to fix.

Delete: ok, can be done.

**Comment by docb** [comment]
fixed in 2.0.2
