### ISSUE TITLE
FM and other presets not compiling

### ISSUE THREAD

**Issue by davephillips** [docb/dbRackCsound#3]
Many preset instruments fail to compile on a Mac Mini M1. The error always refers to the use of ftgenonce, for example

```
error: syntax error, unexpected T_IDENT  (token "ftgenonce")
 line 3:
 >>> itab ftgenonce <<<
Unexpected untyped word itab when expecting a variable

```

where itab may be isine or ifn instead. Any suggestions ? I've checked against the manual, it all looks okay to me but I've been away from Csound code for a while.

Best regards,

dp

**Comment by docb** [comment]
thx,
as a workarround you can do the following:
instead of:
```
instr 1
ifn ftgenonce 0,0,2^15,10,1
```

```
gifn ftgen 0,0,2^15,10,1
instr 1
```
and then replace ifn with gifn in code (if it exists there - i  see that there must be some things to be cleaned up.)

I will look why the ftgenonce is not found on mac os.

**Comment by docb** [comment]
it seems to be complicated so i will first correct the presets to use ftgen.

**Comment by docb** [comment]
fixed in 2.0.2

**Comment by davephillips** [comment]
All good now except wgflute. This:

`asig wgflute .8, kcps, kjet, iatt, idetk, kngain, kvibf, kvamp, isine, 27.5`

should be this:

`asig wgflute .8, kcps, kjet, iatt, idetk, kngain, kvibf, kvamp, gisine, 27.5`

So far that's the only error on loading an instrument. Tests have been only on the mono module, will test the poly versions today.

**Comment by docb** [comment]
ok thanks! i'll correct it in the next release.
> Tests have been only on the mono module, will test the poly versions today

great, i didn't have tested them much.  there are also no factory presets currently.

**Comment by docb** [comment]
please note that there is missing documentation for Csound16:
the correct way to output polyphonic is 
` outch p4*2-1,aoutL,p4*2,aOutR`

**Comment by davephillips** [comment]
I've been testing a simple poly instrument based on a vco2 example, it's working well here. I've been editing some other examples, adding random values and using the INx inputs. Much fun to get reconnected to Csound, thanks a lot for this plugin.
