### ISSUE TITLE
Csound modules not visible on MacOs Mojave

### ISSUE THREAD

**Issue by nay-seven** [docb/dbRackCsound#5]
Hello,
the folder looks correctly created, but no modules visible here on a mac book pro ?
<img width="687" alt="Capture d’écran 2022-10-27 à 20 04 12" src="https://user-images.githubusercontent.com/13808201/198365433-95528c5c-c6b1-4f9f-b278-0b8636750f08.png">

**Comment by docb** [comment]
could you send me the log file please? on mac m1 and mac book pro with big sur it worked so far.

**Comment by nay-seven** [comment]
here it is:

[log.txt](https://github.com/docb/dbRackCsound/files/9882169/log.txt)

**Comment by docb** [comment]
it will probably  fixed by installing libsndfile:
if you have installed homebrew: ```brew install libsndfile```

**Comment by nay-seven** [comment]
looks Mojave is not supported anymore...

"Warning  You are using macOS 10.14.
We (and Apple) do not provide support for this old version.
It is expected behaviour that some formulae will fail to build in this old version.
It is expected behaviour that Homebrew will be buggy and slow.
Do not create any issues about this on Homebrew's GitHub repositories.
Do not create any issues even if you think this message is unrelated.
Any opened issues will be immediately closed without response.
Do not ask for help from MacHomebrew on Twitter.
You may ask for help in Homebrew's discussions but are unlikely to receive a response.
Try to figure out the problem yourself and submit a fix as a pull request.
We will review it but may or may not accept it
......
Error: libsndfile: Failed to download resource "libtool"
Download failed: https://ftpmirror.gnu.org/libtool/libtool-2.4.7.tar.xz

**Comment by docb** [comment]
i remember, because of this issue i have upgraded my mac book, as it became very difficult otherwise.
you may grab the 64bit dylib  [here](https://github.com/bastibe/libsndfile-binaries) and rename and put it here
 `/usr/local/opt/libsndfile/lib/libsndfile.1.dylib`  -- but i am not sure if this works.

i will have a look if i can include it somehow in the plugin.

**Comment by nay-seven** [comment]
Thanks, it doesn't seem to be working, 
no hurry, I'll follow the evolution

**Comment by docb** [comment]
[dbRackCsoundMac.zip](https://github.com/docb/dbRackCsound/files/9885431/dbRackCsoundMac.zip)

could you please try this one?

**Comment by nay-seven** [comment]
Great ! 
Works fine, all 4 modules visible, quick tests with presets ok
Thanks

**Comment by nay-seven** [comment]
For, info i have promoted your modules on my [FB group](https://www.facebook.com/groups/2147926972195324)
people seem interested ;-)

**Comment by nay-seven** [comment]
just also add your website _docb.io_ with your csound-web instruments, 
pretty sure it will interest also the community of this group ;-)

**Comment by docb** [comment]
fixed in 2.0.2
