### ISSUE TITLE
right and left scroll suggestion

### ISSUE THREAD

**Issue by davephillips** [docb/dbRackCsound#8]
Greetings ! I'm enjoying the Csound modules but I have a request. Can you program the editor so the horizontal scroll bar follows the cursor in the edit window ? It's not a show-stopper but the improvement would be noticeable, I think.

Big thanks for these modules, I'm having a great time adding presets drawn from the great variety of Csound-related resources.

Best regards,

Dave Phillips

**Comment by docb** [comment]
fixed in 2.0.3
